Cleanup some inconsistencies

diff --git a/zsh/fpath/compdefcache b/zsh/fpath/compdefcache
--- a/zsh/fpath/compdefcache
+++ b/zsh/fpath/compdefcache
@@ -5,7 +5,7 @@ emulate -L zsh
 setopt local_options extended_glob
 
 local cache_dir=$XDG_CACHE_HOME/zsh/fpath
-local cache_file=$cache_dir/_${1##/*}
+local cache_file=$cache_dir/_${1:t}
 
 # revalidate cache every 20 hours
 if [[ -r $cache_file ]] && ! whence $1 > /dev/null; then
@@ -15,11 +15,11 @@ if [[ -r $cache_file ]] && ! whence $1 > /dev/null; then
 elif [[ ! -e $cache_file || -n $cache_file(#qN.mh+20) ]]; then
     # revalidate cache every 20 hours
     # cache miss, create compdef file
-    if (( ${+commands[${1}]} )); then
+    if whence $1 > /dev/null; then
         zf_mkdir -p $cache_dir
         command $@ > $cache_file
     else
-        echo "compdefcache ERROR: $1 is not available in PATH" >&2
+        echo "compdefcache ERROR: $1 is not executable" >&2
     fi
 else
     # cache hit, do nothing
